import io
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def create_persona_docx(profile: dict) -> io.BytesIO:
    doc = Document()
    
    # Title
    title = doc.add_heading('Baagupadu: Your Authentic Persona & Roadmap', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph('\n')
    
    # 1. Demographics
    demographics = profile.get('life_stage_data', {}).get('demographics', {})
    if demographics:
        doc.add_heading('1. Demographics', level=1)
        p = doc.add_paragraph()
        p.add_run('Name: ').bold = True
        p.add_run(f"{demographics.get('full_name', 'N/A')}\n")
        p.add_run('Desired Role: ').bold = True
        p.add_run(f"{demographics.get('desired_role', 'N/A')}\n")
        p.add_run('Primary Goal: ').bold = True
        p.add_run(f"{demographics.get('primary_goal', 'N/A')}\n")
        doc.add_paragraph('\n')
        
    # 2. Persona Synthesis
    persona = profile.get('persona', {})
    if persona:
        doc.add_heading('2. Your Authentic Self', level=1)
        
        archetype = persona.get('archetype', 'Unknown Archetype')
        p = doc.add_paragraph()
        p.add_run('Core Identity: ').bold = True
        p.add_run(f"{archetype}\n")
        
        summary = persona.get('summary', '')
        if summary:
            doc.add_paragraph(summary)
            
        strengths = persona.get('key_strengths', [])
        if strengths:
            doc.add_heading('Key Strengths', level=2)
            for strength in strengths:
                doc.add_paragraph(strength, style='List Bullet')
                
        growth = persona.get('growth_areas', [])
        if growth:
            doc.add_heading('Growth Areas', level=2)
            for area in growth:
                doc.add_paragraph(area, style='List Bullet')
                
        doc.add_paragraph('\n')
        
    # 3. Career Roadmap (Guidance)
    roadmap = profile.get('guidance', {}).get('roadmap', {})
    if roadmap:
        doc.add_heading('3. Career Roadmap', level=1)
        
        primary_path = roadmap.get('primary_career_path', {})
        if primary_path:
            p = doc.add_paragraph()
            p.add_run('Recommended Career Path: ').bold = True
            p.add_run(f"{primary_path.get('title', 'Unknown')}\n")
            doc.add_paragraph(primary_path.get('reasoning', ''))
            
        # We can expand this later when we update the prompt to be more step-by-step
        
        milestones = roadmap.get('action_plan', [])
        if milestones:
            doc.add_heading('Action Plan', level=2)
            for step in milestones:
                if isinstance(step, dict):
                    timeframe = step.get('timeframe', 'Action')
                    action = step.get('action', '')
                    p = doc.add_paragraph(style='List Bullet')
                    p.add_run(f"{timeframe}: ").bold = True
                    p.add_run(action)
                else:
                    doc.add_paragraph(str(step), style='List Bullet')

    doc.add_paragraph('\n')
    footer = doc.add_paragraph()
    footer_run = footer.add_run('Generated by Baagupadu AI Coach (Sahayam)')
    footer_run.italic = True
    footer_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    
    return file_stream
